### ISSUE TITLE
Plugin Activation Message Refinements, Part 2

### ISSUE THREAD

**Issue by swissspidy** [GoogleForCreators/web-stories-wp#3906]
## Feature Description

1. According to the design, the dark themed plugin activation message has a scrim at the bottom for all images.
1. "Welcome to the Web Stories for WordPress beta." should wrap better to the second line.

## Additional Context

Screenshot:

<img width="949" alt="Screenshot 2020-08-14 at 11 39 32" src="https://user-images.githubusercontent.com/841956/90236379-f9d59580-de22-11ea-8190-2bf24afc1f3d.png">

CSS copied from Figma:

```css
background: linear-gradient(180deg, #020219 37.25%, rgba(28, 6, 25, 0) 100%);
transform: matrix(1, 0, 0, -1, 0, 0);
```

So something like that should work:

```css
&::after {
	content: "";
    display: block;
    background: linear-gradient(180deg, #020219 37.25%, rgba(28, 6, 25, 0) 100%);
    transform: matrix(1, 0, 0, -1, 0, 0);
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    width: 100%;
    height: 80px;
}
```

---

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Implementation Brief

* Add scrim
* Add `max-width: 270px;` on first container to improve text wrapping
* Add `max-width: 440px;` on the last container to improve text wrapping and spacing between 2nd and 3rd container
